import { ShotType } from "./schemas";

export const POSES: Record<ShotType, string[]> = {
  "full_body": [
    "Walking towards camera with confidence, cityscape background",
    "Leaning against a textured wall, one leg crossed, casual stance",
    "Sitting on a modern chair, leaning forward, elbows on knees",
    "Standing profile view, looking over shoulder, dramatic lighting",
    "Jumping/Mid-air action pose, dynamic energy",
    "Walking away from camera, turning head back slightly",
    "Sitting on steps, relaxed posture, hands loosely clasped",
    "Standing wide stance, hands in pockets, power pose",
    "Leaning back on hands, sitting on ground, looking up at sky",
    "Walking briskly, checking watch/phone, busy urban vibe",
    "Standing with weight on one leg, hand on hip, fashion model stance",
    "Sitting cross-legged on floor, casual and approachable",
    "Leaning against a railing, looking out at a view",
    "Stride capture, freezing motion of walking, coat flowing",
    "Standing tall, arms crossed, serious executive look",
    "Sitting on a high stool, one foot on rest, one on ground",
    "Crouching down, low angle shot, street style",
    "Leaning forward against a table/surface, engaging with viewer",
    "Spinning movement, capturing motion blur in clothing",
    "Standing straight, hands behind back, formal posture",
    "Lounging on a sofa, relaxed but elegant",
    "Walking down stairs, looking at camera",
    "Standing in a doorway, silhouetted against light",
    "Sitting on a ledge, legs dangling, carefree vibe",
    "Running towards camera, fitness/active context",
    "Standing with back to wall, one foot propped up",
    "Kneeling, engaging with something on the ground",
    "Leaning against a car or vehicle, road trip vibe",
    "Walking with a bag/prop, natural lifestyle movement",
    "Standing with arms raised, celebrating or stretching",
    "Sitting on the floor, leaning back on hands, knees up",
    "Walking through a crowd (blurred background), focus on subject",
    "Standing on a balcony, wind in hair",
    "Sitting at a cafe table, looking out window",
    " leaning on a pillar, casual observation",
    "Standing with hands in jacket pockets, cool winter vibe",
    "Sitting on a bench, reading or looking at phone",
    "Walking away, looking back over shoulder",
    "Standing confidently, adjusting tie/collar/accessory",
    "Leaning forward with hands on knees, resting active pose"
  ],
  "upper_body": [
    "Arms crossed, confident smile, business portrait",
    "Hand on chin, thoughtful expression, slight head tilt",
    "Adjusting glasses/hair, candid moment",
    "Holding a coffee cup, looking sideways, lifestyle vibe",
    "Hands clasped in front, attentive listening posture",
    "Leaning forward, elbows on table, engaging eye contact",
    "Profile view, looking at light source, dramatic mood",
    "Laughing naturally, hand near face, joyful expression",
    "Straight on, neutral expression, passport/ID style clarity",
    "Looking over shoulder, mysterious vibe",
    "Hands gesturing while talking, dynamic speaker pose",
    "Holding a prop (book/tablet), professional context",
    "Resting head on hand, bored or relaxed expression",
    "Fixing collar/tie, sharp and prepared",
    "Looking up slightly, catchlight in eyes, hopeful look",
    "Hands in pockets (visible at waist), casual stance",
    "Turning towards camera, motion blur suggestion",
    "Holding jacket over shoulder, casual end-of-day vibe",
    "Hands on hips, authoritative stance",
    "Leaning against wall, shoulder first, relaxed",
    "Looking down at phone/notes, concentrated",
    "Hands interacting with environment (railing, table)",
    "Drinking from a bottle/cup, natural action",
    "Pointing or gesturing towards something off-camera",
    "Shrugging, playful expression",
    "Covering face partially with hand/hair, artistic style",
    "Looking through a window/glass, reflection play",
    "Hands behind head, relaxed executive pose",
    "Tying a scarf or adjusting accessory",
    "Holding a camera/tool, showing occupation/hobby",
    "Clapping or hands together, congratulatory vibe",
    "Resting deep in thought, looking away",
    "Straight posture, chin up, proud expression",
    "Leaning on one elbow, asymmetrical composition",
    "Action of writing or typing, busy professional",
    "Holding a bouquet or object, soft mood",
    "Pulling jacket tight, cold weather or cozy vibe",
    "Hands clearly visible, using hand gestures",
    "Looking past camera, dreamy expression",
    "Direct intense eye contact, serious mood"
  ],
  "face": [
    "Direct eye contact, slight smile, approachable",
    "Looking off-camera, dramatic lighting (Rembrandt)",
    "Laughing, eyes crinkled, genuine joy",
    "Serious intense gaze, high contrast lighting",
    "Profile silhouette, artistic and moody",
    "Looking up, soft lighting, angelic/hopeful",
    "Winking or playful expression",
    "Looking down, shy or introspective",
    "Eyes closed, peaceful or sensing environment",
    "Slight frown or serious concentration",
    "Three-quarter view, classic portrait angle",
    "Looking over sunglasses/glasses",
    "Blowing bubblegum or playful facial action",
    "Hand framing the face, fashion editorial style",
    "Hair blowing across face, dynamic and messy",
    "Wet look/rain on face, textured and raw",
    "Extreme heavy shadow on one side (Split lighting)",
    "Looking back over shoulder (tight crop)",
    "Surprised expression, eyes wide",
    "Biting lip or subtle nervous/anticipation look",
    "Slight smirk, confident and knowing",
    "Looking straight up at camera (birds eye facial)",
    "Chin resting on hands, sweet/innocent pose",
    "Grimacing or strong emotional reaction",
    "Makeup focus, eyes closed or looking down",
    "Lighting a match or glow on face from below",
    "Looking through fingers/hand",
    "Screaming or mouth open (dynamic emotion)",
    "Calm neutral expression, detailed skin texture",
    "Tongue out or silly face (if appropriate)",
    "Teeth showing, big wide smile",
    "Looking at something very close (cross-eyed slightly)",
    "Reflection in eyes focus (macro style)",
    "Half face in shadow, half in light",
    "Face pressed against glass (creative)",
    "Looking side-eye, skeptical or curious",
    "Head tilted back, laughing at ceiling",
    "Head tilted down, looking up through brows (Kubrick stare style but softer)",
    "Detailed focus on iris/eye color",
    "Soft focus, dreamy, romantic gaze"
  ]
};
